-- Supabase RLS Permission Fix for Portfolio
-- Run this in Supabase SQL Editor to allow public read/write permissions from Admin & Website

ALTER TABLE IF EXISTS profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS education DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS experiences DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS project_features DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS project_technologies DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS project_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS certificates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS testimonials DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS contact_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS visitors DISABLE ROW LEVEL SECURITY;
